### ISSUE TITLE
Slack channel invite not working?

### ISSUE THREAD

**Issue by davidfrey** [open-guides/og-aws#161]
The invite tool accepts my e-mail address and tells me to check my inbox, but no invite ever arrives.

**Comment by stevear22** [comment]
thought it was just me :)

**Comment by jlevy** [comment]
Looking at it. In the meantime, so we don't lose you, send an e-mail to og-aws@lexikon.io asking to join and I'll do it manually!

**Comment by jlevy** [comment]
This should be fixed now. If you don't already have an invite feel free to try it out again! https://og-aws.slack.lexikon.io/

Comment here or e-mail that address if you still see issues.

**Comment by PatMyron** [comment]
@jlevy still experiencing this

**Comment by PatMyron** [comment]
@jlevy @QuinnyPig tried that email as well and got this reponse:
`Your message wasn't delivered to og-aws@lexikon.io because the address couldn't be found, or is unable to receive mail.`

`The response was:
550 5.1.1 The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser l110sor8732975otc.182 - gsmtp`

**Comment by PatMyron** [comment]
related: https://github.com/Miserlou/zappa-slack-inviter/issues/5

guess I signed up a while ago 🧐
