### ISSUE TITLE
Include GorillaStack Logo In Services / Tools Infographic

### ISSUE THREAD

**Issue by Ollibe13** [open-guides/og-aws#522]
Per my discussion with @QuinnyPig  we would love to have the GorillaStack logo included in the infographic. While GorillaStack covers a number of automation scenarios, Cost Management would probably be the most appropriate section.

Thank you
![gorillastack-large-blue 1](https://user-images.githubusercontent.com/22188048/31590441-f783e58e-b25b-11e7-8bdf-0e3150f6d7c9.png)

**Comment by ThanosBaskous** [comment]
Hi @Ollibe13, thank you for your submission and for your interest in the Open Guide to AWS. We are trying to keep the graphic of services and tools to the most well known and significant set in a given space in order to keep the graphic manageable and the guide navigable, and I don't think that GorillaStack (yet) qualifies as being significant enough to squeeze out the others.

If you disagree with my (quick) assessment of significance of GorillaStack relative to the others in the graphic, I'd be happy to review any information that you submit to support that.

I'm closing this issue, but will will reopen for discussion if new information is added.

Thanks again.

**Comment by Ollibe13** [comment]
Hi @ThanosBaskous ,

Thanks for the direct reply - much appreciated. I also appreciated getting to know a bit more at re:Invent about the challenges you face in determining these kinds of things.

I respectfully submit batch.ly no longer exists as a brand and cloudyn is in the process of being migrated to an azure shop.

When it comes to cost optimisation & automation, GorillaStack without any payment or sponsorship has been organically highlighted by AWS as a key tool for cost optimisation at re:Invents '15, '16 & '17. 2016's recommendation came from Keith Jarrett, the Amazon's global head of cost optimisation.

https://www.youtube.com/watch?v=CoUE2w6Pr3w
https://www.youtube.com/watch?v=JA64Eeucw0k&feature=youtu.be&t=10m11s
https://www.youtube.com/watch?v=iOWNZqG0RN4&feature=youtu.be&t=26m35s

Given that we are recommended by AWS ahead of our competition, both in public talks and directly to customers (AWS make up a big part of our channel referrals) as a tool for cost management, I'd love for you to reconsider based on this new information.

Thank you Thanos

Oliver

**Comment by ThanosBaskous** [comment]
Hi @Ollibe13, thanks for bringing this back up - you make reasonable arguments. I'm sharing your proposal to add GorillaStack to the Services / Tools infographic to the other editors of the guide and will let you know the outcome.

**Comment by Ollibe13** [comment]
Thank you!
