### ISSUE TITLE
Add section/expand ECS section with information about Fargate

### ISSUE THREAD

**Issue by pgrzesik** [open-guides/og-aws#563]
AWS recently announced great new service: https://aws.amazon.com/fargate/, it would be awesome to have a seperate secion dedicated to Fargate or at least a mention in ECS section.

**Comment by pgrzesik** [comment]
Just a little bump - if you think it's a good idea to add such section, I'll gladly handle PR for that, just let me know :)

**Comment by ThanosBaskous** [comment]
That would be great @pgrzesik!

One thing that we request is that you do a version of the section in Quip first - example: https://quip.com/UrBzAwuYk4o4

The reason that we ask this is so that we can use Quip's collaboration features to more quickly help you edit the section - the turnaround ends up being much faster than GH. Once the section is reasonably mature, we'll ask you to move it to a PR.

Assuming that you're on board with doing it that way, feel free to share the link with me, jlevy, and cquinn in the og-aws slack when you are ready for someone to take a look at it.

Does that sound good?

Thanks!

**Comment by pgrzesik** [comment]
hey @ThanosBaskous, that sounds great! I will be offline for the next week, but if nobody will pick this topic up, I'd like to prepare a Quip version :) I'm just wondering - should it be a totally new section or a part of existing ECS, what do you guys think ?

**Comment by ThanosBaskous** [comment]
Hi @pgrzesik, I think that the organizational model that makes the most sense in the long run is having a "section group" for Fargate + (ECS and EKS), parallel to the section group for Load Balancers + (CLB and ALB) (search through the latest version of the guide to see what I'm talking about). For now, a new section for Fargate, ideally positioned above ECS, would be fine and a good starting place.

**Comment by pgrzesik** [comment]
Related PR: https://github.com/open-guides/og-aws/pull/586
